### ISSUE TITLE
Game should find data files regardless of case

### ISSUE THREAD

**Issue by angered-ghandi** [angered-ghandi/OpenAOE#2]
Since AOE was built in the 90s for Windows, the data files tend to be ALLCAPS (although I've seen them all lower too). The game shouldn't care which case they are on a case sensitive file system. Instead of hardcoding paths to the data files, scan the data directory and use a case insensitive equals to find the file that's desired.

**Comment by EggsSeriously** [comment]
Yeah, some of the files are lower, upper, and mixed it seems. Renaming all the files in a dir to lower works, but it's a pain.
