### ISSUE TITLE
Rename Age structs in the dat crate

### ISSUE THREAD

**Issue by angered-ghandi** [angered-ghandi/OpenAOE#30]
There are a set of structs called `Age`, `AgeEffect`, etc in the `dat` crate. These names are inaccurate as they have nothing to do with the ages in the game, but are instead groups of effects that research can have in the game.

We should rename them to `ResearchEffectGroup`, `ResearchEffect`, and `ResearchEffectValue`.

**Comment by phrohdoh** [comment]
I am doing this right now.
