### ISSUE TITLE
Render "deltas" for graphics

### ISSUE THREAD

**Issue by angered-ghandi** [angered-ghandi/OpenAOE#37]
Some graphics, such as buildings, use "deltas" to render player colors and other things. Currently, OpenAOE ignores these deltas, so you get weird things like this:
![missing-decals](https://cloud.githubusercontent.com/assets/20009343/17084999/04563fbe-5182-11e6-8d26-e1247314b701.png)

This issue is to implement the delta rendering.

**Comment by phrohdoh** [comment]
Do you know the criteria for each delta entry/index?

**Comment by angered-ghandi** [comment]
Each graphic in the empires.dat has a list of graphic id and offset to represent the deltas.
