### ISSUE TITLE
Locate the mouse cursor graphic

### ISSUE THREAD

**Issue by angered-ghandi** [angered-ghandi/OpenAOE#39]
Should look like:
![cursor](https://cloud.githubusercontent.com/assets/20009343/17282487/2331e058-575b-11e6-805d-3b100aa3a951.png)

Find the SLP ID.

**Comment by Xinayder** [comment]
SLPs 51000-51010 are mouse cursors in INTERFAC.DRS.

SLP 51000 has 7 cursors:
![](https://u.pomf.is/hulnzf.png)

**Comment by angered-ghandi** [comment]
Thanks so much for finding those! I've filed #49 to use them in game.
