### ISSUE TITLE
Support stable, beta, or nightly (or a combination).

### ISSUE THREAD

**Issue by phrohdoh** [angered-ghandi/OpenAOE#61]
I run `nightly-x86_64-apple-darwin unchanged - rustc 1.14.0-nightly (6dc035ed9 2016-10-15)` but OpenAOE builds just fine on `stable-x86_64-apple-darwin unchanged - rustc 1.12.0 (3191fbae9 2016-09-23)`.

Is there a particular version we should develop against?
If so, we should note that in the readme (or push the rustup team to support a per-project toolchain override).

**Comment by angered-ghandi** [comment]
Travis CI is configured to build it against stable and nightly, so it should always work on both of those. I used to have it build against beta, but there was a breaking change in beta that caused it to fail for a while. We can add that back in now that there's a way to configure Travis to not fail the build if beta breaks.

**Comment by angered-ghandi** [comment]
Added beta back to the Travis build as an allowed failure: c108e0709113b4dd99601daf9ef6cfdba70e1f24

**Comment by phrohdoh** [comment]
Would you also be interested in automating tagged releases (even if just for testing)?
I've set this up for a Windows build via Appveyor for one of my tools for work (ref https://github.com/Phrohdoh/provider_formulary_json_searcher).

Of course Travis could handle GNU/Linux and macOS.

**Comment by angered-ghandi** [comment]
Yeah, that'd be awesome.

**Comment by phrohdoh** [comment]
Cool.
Could you provide me with:
- The encrypted secure auth token
- A list of channels you'd like Appveyor to build
- Which triples you'd like to target

**Comment by angered-ghandi** [comment]
Encrypted deploy key:

```
1ALD6ZyuwDl2qMw5PgF38OU2N7oayMbCaOI7Ib8qYuNKusLq+XhzsZXgo4OzljyA
```

Nightly GNU is probably a good start: x86_64-pc-windows-gnu

**Comment by phrohdoh** [comment]
Let's see how #63 works out.
