### ISSUE TITLE
Implement player color handling when loading SLP shapes

### ISSUE THREAD

**Issue by angered-ghandi** [angered-ghandi/OpenAOE#9]
Currently, the code that reads SLP files skips over the player color pixels (so that they're always black):
https://github.com/angered-ghandi/OpenAOE/blob/master/crates/file_formats/slp/src/slp.rs#L300

The SLP interface will need to be modified to take in a player color palette index as a parameter. AOE had several player colors spaced apart by powers of two, so only the index of the first player color really matters. The rest of the colors are made by doing a binary OR against the first color index.

The easiest way to test this (visually) is probably to add a command-line parameter to the [slp_viewer tool](https://github.com/angered-ghandi/OpenAOE/blob/master/tools/slp_viewer/src/main.rs) to take the palette index (optionally), and pass that to the SLP crate.

**Comment by phrohdoh** [comment]
I have [a branch for parsing player color](https://github.com/Phrohdoh/OpenAOE/tree/player-color).

![screen shot 2016-07-12 at 8 36 45 pm](https://cloud.githubusercontent.com/assets/4861023/16789818/464387b6-4876-11e6-8f69-9ce78a038b68.png?raw=true)

Discussion regarding my opinion on how we should approach player color:

```
Phrohdoh: Xinayder: just read your bit about turtlepack and it made me remember what we're missing
Xinayder: what?!
Phrohdoh: the aoe engine overlayed player-color-only sprites onto other sprites
Phrohdoh: so none of the base sprites contain player color
Xinayder: so, how do we fix that?
Phrohdoh: We figure out which sprites should be used together and write some metadata so we can render multiple slps
Phrohdoh: structures do the overlay I mentioned, units don't, the color is embed directly in units
Phrohdoh: test 683
Phrohdoh: Xinayder: http://i.imgur.com/sbljsxz.png
Phrohdoh: cargo run --release -- 683 --drs "/Users/thill/Desktop/GAME/DATA/GRAPHICS.DRS" --interfac "/Users/thill/Desktop/GAME/DATA/INTERFAC.DRS" --player 6
Phrohdoh: we should read as player 1 and apply remaps a single time on load (and apply the color ramp as necessary)
Xinayder: I mean, how to color the structures?
Phrohdoh: We'd have metadata about which graphic overlays the structure. we parse the overlay as player 1 and apply the real player remap ramp later when creating the spritesheet
Phrohdoh: (we can merge the structure and overlay when creating the spritesheet)
```

Applying `player-color` on top of [`makefiles`](https://github.com/Phrohdoh/OpenAOE/commit/055189e430c3da36762096f9bbfbeb69ae3c3e6a) this can easily be tested with `slp_viewer` by running:

`cargo run --release -- 683 --drs GAME/DATA/GRAPHICS.DRS --interfac GAME/DATA/INTERFAC.DRS`

Let me know what you think of the approach I've taken.
I wasn't pleased with having to add `pub player_index: u8` to `SlpLogicalShape`, so if this is possible without that great.
